record_list = [
    ("Patient", "Uh, hi, Doctor? May I come in?"),
    ("Doctor", "Of course, come on in! Take a seat, Priya. I’m Dr. Patel. How do you say your name?"),
    ("Patient", "Thanks. It’s Priya Sharma, like PREE-yah SHAR-mah."),
    ("Doctor", "Got it, Priya. Nice to meet you! Mind if I ask your age?"),
    ("Patient", "I’m 28."),
    ("Doctor", "Alright, great. So, what’s going on? Why’re you here today?"),
    ("Patient", "I’ve been, um, really dizzy lately, and just… exhausted. It’s been like a month, and it’s freaking me out a bit."),
    ("Doctor", "I’m sorry to hear that. Can you tell me about the dizziness? Is it, like, the room spinning, or more lightheaded?"),
    ("Patient", "Definitely lightheaded, like I might pass out. Happens a few times a day, especially when I stand up fast."),
    ("Doctor", "Hmm, okay. And the fatigue? When’s it worst?"),
    ("Patient", "Mornings are rough. I wake up feeling like I barely slept, even after 8 hours. By afternoon, I’m dragging."),
    ("Doctor", "That sounds tough. Any past medical stuff? Conditions, surgeries?"),
    ("Patient", "Just my appendix out at 16. No meds, except maybe ibuprofen for headaches sometimes."),
    ("Doctor", "Good to know. Any allergies?"),
    ("Patient", "Nope, none."),
    ("Doctor", "Family history? Like diabetes or heart issues?"),
    ("Patient", "Yeah, my mom’s got type 2 diabetes, and my dad had a heart attack a few years back."),
    ("Doctor", "Thanks for that. What’s your day-to-day like? Job, diet, exercise?"),
    ("Patient", "I’m a teacher, so I’m on my feet a lot. I try to eat healthy—fruits, veggies—but I skip breakfast sometimes ‘cause I feel off. I don’t exercise much, maybe a walk weekly. Sleep’s 10:30 p.m. to 6 a.m."),
    ("Doctor", "Alright. Caffeine, alcohol, smoking? Water intake?"),
    ("Patient", "One or two coffees daily, a cocktail maybe monthly. No smoking. Probably 4 glasses of water a day."),
    ("Doctor", "Okay, Priya. Dizziness and fatigue could be dehydration, low blood pressure, or something like anemia. Family history’s a factor too. Let’s do blood tests for iron, blood sugar, and a few others. We’ll check your blood pressure today too."),
    ("Patient", "Blood tests? Um, do those hurt?"),
    ("Doctor", "Just a quick pinch, I promise. It’ll help us figure this out. For now, try 8 glasses of water daily and small, regular meals. Keep a symptom diary—time, dizziness, fatigue, what you ate or did."),
    ("Patient", "Okay, I can do that. How do I track it?"),
    ("Doctor", "Jot down when symptoms hit, how bad they are, and anything related, like meals. Bring it next week. I’ll set up the blood test referral and check your blood pressure before you go."),
    ("Patient", "Thanks, Dr. Patel. I just wanna feel normal again."),
    ("Doctor", "I hear you, Priya. We’ll sort this out. If anything gets worse, call us, okay?"),
    ("Patient", "Will do. Thanks for listening."),
    ("Doctor", "My pleasure. Let’s check that blood pressure. See you next week!"),
    ("Patient", "Thanks, Doctor. See you.")
]


recorded_list2 = [
    # 1) Casual Introduction
    ("Patient", "Uh, hi, Doctor? May I come in?"),
    ("Doctor", "Of course, please come in! Have a seat. I’m Dr. Sharma. What’s your full name, please?"),
    ("Patient", "I’m Rina Das."),
    ("Doctor", "Nice to meet you, Rina. How old are you?"),
    ("Patient", "I’m 32 years old."),
    ("Doctor", "Okay. What do you do for a living?"),
    ("Patient", "I work as a software engineer."),
    ("Doctor", "Ah, that must involve a lot of screen time. Where do you live?"),
    ("Patient", "I live in Kolkata."),
    ("Doctor", "Got it. Do you have any allergies that I should know about?"),
    ("Patient", "No, I don’t have any known allergies."),
    ("Doctor", "Great. Are you on any current medications?"),
    ("Patient", "Yes, I take Metformin 500mg daily for my type 2 diabetes."),

    # 2) Collecting the Patient's Problems
    ("Doctor", "Alright, Rina. What brings you in today?"),
    ("Patient", "I’ve been having constant headaches for the last two weeks. Also, sometimes my vision gets blurry after working for a few hours."),
    ("Doctor", "Hmm, anything else?"),
    ("Patient", "Yes, I’ve also been feeling unusually tired, especially in the afternoons."),
    ("Doctor", "Okay, anything else bothering you?"),
    ("Patient", "Actually, yes. Occasionally, I feel shortness of breath when climbing stairs."),
    ("Doctor", "Understood. How would you rate your headache on a scale of 1 to 10?"),
    ("Patient", "It’s about a 6 most of the time, but sometimes it spikes to 8."),
    ("Doctor", "When was the last time you checked your blood sugar levels?"),
    ("Patient", "Last week. It was 175 mg/dL before lunch."),
    
    # 3) Patient's Previous Medical History
    ("Doctor", "Do you have any previous history of other illnesses or conditions?"),
    ("Patient", "Yes. Apart from diabetes, I had hypothyroidism diagnosed two years ago. I’m on Levothyroxine 50 mcg daily."),
    ("Doctor", "Any surgeries in the past?"),
    ("Patient", "I had my appendix removed when I was 21."),
    ("Doctor", "Okay. Any family history of chronic illnesses like hypertension or heart disease?"),
    ("Patient", "Yes, my father had hypertension and my mother has osteoarthritis."),
    ("Doctor", "Have you been taking your thyroid and diabetes medication regularly?"),
    ("Patient", "Mostly, but I did miss a few doses during a hectic work schedule last month."),
    ("Doctor", "Alright. Have you consulted anyone else about these recent symptoms?"),
    ("Patient", "Yes, I saw a neurologist two months ago for occasional migraines, and I was prescribed Sumatriptan, but I only used it twice."),
    ("Doctor", "Did it help with the migraines?"),
    ("Patient", "A bit, but this headache feels different."),

    # 4) Expected Causes of the Problem
    ("Doctor", "Okay. Based on what you’ve described, the headache and blurred vision might be due to poorly controlled blood sugar, eye strain from screen time, or thyroid imbalance."),
    ("Doctor", "The tiredness could be from your thyroid, blood sugar fluctuations, or even iron deficiency."),
    ("Doctor", "And the shortness of breath could be from low fitness, anemia, or potentially something heart-related, though less likely given your age."),
    ("Doctor", "But we’ll need some tests to be sure."),

    # 5) Suggestions or Advice
    ("Doctor", "I’ll suggest a few things for now:"),
    ("Doctor", "1. Blood tests: CBC, thyroid profile, fasting and postprandial blood sugar, HbA1c, and serum ferritin."),
    ("Doctor", "2. Eye examination to check for diabetic retinopathy or vision changes."),
    ("Doctor", "3. Reduce continuous screen time. Follow the 20-20-20 rule: every 20 minutes, look at something 20 feet away for 20 seconds."),
    ("Doctor", "4. Resume regular intake of your thyroid and diabetes medications without skipping."),
    ("Doctor", "5. Try to get at least 7 hours of sleep and engage in light physical activity daily."),
    ("Doctor", "6. Monitor your headaches. If they worsen or new symptoms occur, we may need to do a brain MRI."),
    ("Doctor", "I’ll write a referral for a nutritionist as well, to better manage your diet."),
    ("Patient", "Thank you, Doctor. I’ll follow up with the tests."),
    ("Doctor", "You're welcome, Rina. Let’s review your results in a week and adjust your treatment accordingly.")
]
